# System Info Now Configuration
output:
  format: json
  directory: output
  filename: system_data.json

logging:
  level: INFO
  directory: logs

project:
  root_dir: "." # Default to current directory, can be set to absolute path

collectors:
  system: true # WARNING: This includes sensitive system data, be careful where you send it
  python: true
  javascript: true